---
# 'version' is the semantic version of the configuration file format.
version: 0.1.0

extraSANs:
  - 192.168.13.112

extraContainerdEnv:
  http_proxy: http://192.168.13.112:3128
  https_proxy: http://192.168.13.112:3128
  no_proxy: 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
  HTTP_PROXY: http://192.168.13.112:3128
  HTTPS_PROXY: http://192.168.13.112:3128
  NO_PROXY: 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8

extraKubeAPIServerArgs:
  --bind-address: 0.0.0.0
  --advertise-address: 192.168.13.112

extraKubeletArgs:
  --node-ip: 192.168.13.112

# extraKubeProxyArgs:
#   --nodeport-addresses: 192.168.13.112
#   --bind-address: 0.0.0.0

# addons:
#   - name: dns
#     args: [1.1.1.1]
#   - name: metallb
#     args: ["192.168.13.200-192.168.13.210"]
#   - name: ingress
#   - name: metrics-server
#   - name: observability
#   - name: hostpath-storage
#   - name: rbac
#   - name: registry

