apiVersion: apps/v1
kind: Deployment
metadata:
  name: fov-quicklook-coordinator
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: fov-quicklook-coordinator
  template:
    metadata:
      labels:
        app: fov-quicklook-coordinator
    spec:
      containers:
        - name: fov-quicklook-coordinator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - sh
            - -c
            - |
              set -e
              alembic upgrade head
              exec python -m quicklook.coordinator.api
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fov-quicklook
                  key: db_password
            - name: QUICKLOOK_db_url
              value: postgresql://quicklook:$(DB_PASSWORD)@fov-quicklook-db:5432/quicklook
            - name: QUICKLOOK_data_source
              value: {{ .Values.data_source | quote }}
            {{- include "fov-quicklook.env.s3_tile" . | nindent 12 }}
            {{- include "fov-quicklook.env.s3_test_data" . | nindent 12 }}
          ports:
            - containerPort: 9501
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          resources: {{ toYaml .Values.coordinator.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: fov-quicklook-coordinator
spec:
  selector:
    app: fov-quicklook-coordinator
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 9501
      targetPort: 9501
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fov-quicklook-coordinator-policy
spec:
  podSelector:
    matchLabels:
      app: fov-quicklook-coordinator
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: fov-quicklook-generator
        - podSelector:
            matchLabels:
              app: fov-quicklook-frontend
      ports:
        - protocol: TCP
          port: 9501
