apiVersion: apps/v1
kind: Deployment
metadata:
  name: quicklook-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quicklook-db
  template:
    metadata:
      labels:
        app: quicklook-db
    spec:
      initContainers:
        - name: init-permissions
          image: 'busybox'
          command: ['sh', '-c', 'chown -R 999:999 /var/lib/postgresql/data']
          volumeMounts:
            - name: quicklook-db
              mountPath: /var/lib/postgresql/data
      containers:
        - name: quicklook-db
          image: 'postgres:16'
          env:
            - name: POSTGRES_USER
              value: quicklook
            - name: POSTGRES_DB
              value: quicklook
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quicklook-db
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: quicklook-db
              mountPath: /var/lib/postgresql/data
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
      volumes:
        - name: quicklook-db
          persistentVolumeClaim:
            claimName: quicklook-db
---
apiVersion: v1
kind: Service
metadata:
  name: quicklook-db
spec:
  selector:
    app: quicklook-db
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quicklook-db
spec:
  {{- if .Values.db_storage_class }}
  storageClassName: {{ .Values.db_storage_class }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: quicklook-db-policy
spec:
  podSelector:
    matchLabels:
      app: quicklook-db
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: quicklook-coordinator
      ports:
        - protocol: TCP
          port: 5432
