{{- if .Values.use_vault }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: fov-quicklook
spec:
  path: "{{ .Values.global.vaultSecretsPathPrefix }}/fov-quicklook"
  type: Opaque
  keys:
    - s3_repository_access_key
    - s3_repository_secret_key
    - s3_tile_access_key
    - s3_tile_secret_key
    - db_password
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: fov-quicklook
type: Opaque
data:
  s3_repository_access_key: quicklook
  s3_repository_secret_key: password
  s3_tile_access_key: quicklook
  s3_tile_secret_key: password
  db_password: password
{{- end }}
