"""create-quicklook-meta

Revision ID: f759fd975f63
Revises: 0ecedbb5dce2
Create Date: 2024-10-09 16:57:42.922245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f759fd975f63'
down_revision: Union[str, None] = '0ecedbb5dce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quicklook_meta',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('body_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['quicklooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quicklook_meta')
    # ### end Alembic commands ###
