apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      nodeSelector:
        minio: "true"  # このラベルに一致するノードのみにスケジュールされる
      containers:
      - name: minio
        image: quay.io/minio/minio:RELEASE.2024-08-26T15-33-07Z-cpuv1
        args:
          - server
          - "http://192.168.13.{121...122}:9000/data"
          # - "/data"
          - --console-address
          - ":9001"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
          - mountPath: /data
            name: data
        env:
          - name: MINIO_ROOT_USER
            value: minio
          - name: MINIO_ROOT_PASSWORD
            value: password
      hostNetwork: true
      volumes:
        - name: data
          hostPath:
            path: /mnt/ssd1/minio
