apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  type: LoadBalancer
  # loadBalancerIP is optional. MetalLB will automatically allocate an IP 
  # from its pool if not specified. You can also specify one manually.
  loadBalancerIP: 192.168.13.201
  ports:
    - name: minio
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: minio-cluster-ip
spec:
  selector:
    app: minio
  type: ClusterIP
  clusterIP: None
  ports:
    - name: minio
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
